#!/bin/bash

echo "🚀 GitHub Repository Setup Script"
echo "=================================="
echo ""
echo "📋 Steps to push to GitHub:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named 'voice-appointment-system' (or your preferred name)"
echo "3. DO NOT initialize with README, .gitignore, or license"
echo "4. Copy the repository URL (it will look like: https://github.com/yourusername/voice-appointment-system.git)"
echo ""
echo "5. Then run these commands:"
echo ""
echo "   # Add the remote origin (replace with your actual repository URL)"
echo "   git remote add origin https://github.com/yourusername/voice-appointment-system.git"
echo ""
echo "   # Push to GitHub"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "6. Your repository will be live at: https://github.com/yourusername/voice-appointment-system"
echo ""
echo "🎉 Done! Your voice appointment system is now on GitHub!" 